name: CI Pipeline

on:
  push:
    branches:
      - main
      - member5-devops

  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show Current Directory
        run: |
          pwd
          ls -la
          find . -maxdepth 2

      - name: Check Docker Compose
        run: |
          if [ -f docker-compose.yml ]; then
            echo "✅ docker-compose.yml found"
          else
            echo "❌ docker-compose.yml not found"
            exit 1
          fi

      - name: Check Required Folders
        run: |
          for folder in backend frontend ai-engine database deployment
          do
            if [ -d "$folder" ]; then
              echo "✅ $folder exists"
            else
              echo "❌ $folder NOT FOUND"
              exit 1
            fi
          done

      - name: Finish
        run: echo "🚀 CI Passed Successfully"