name: CI Pipeline

on:
 push:
    branches:
      - main
      - member5-devops

  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show Project Structure
        run: |
          pwd
          ls -R

      - name: Check Required Folders
        run: |
          test -d deployment
          test -d database
          test -d notebooks
          test -d scripts
          echo "Required folders found"

      - name: Check Docker Compose
        run: |
          test -f docker-compose.yml
          echo "docker-compose.yml found"

      - name: Finish
        run: echo "CI Passed Successfully"